name: "Build"
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Start Supporting Services
        run: ./scripts/setup.sh
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
        with:
          gradle-version: 7.3
          arguments: clean test build artifactoryPublish --info -PIS_SNAPSHOT_BUILD=true
