name: "CI"
on: [pull_request]
jobs:
  Detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "detekt"
        uses: alaegin/Detekt-Action@v1.22.0-RC3
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: .detekt.yml
  Build-And-Publish-A-Snapshot:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20
      - name: Start Supporting Services
        run: ./scripts/setup.sh
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2
        env:
          PACKAGE_STORE_USERNAME: ${{ secrets.PACKAGE_STORE_USERNAME }}
          PACKAGE_STORE_TOKEN: ${{ secrets.PACKAGE_STORE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        with:
          gradle-version: 8.2.1
          arguments: clean test build publish --info --stacktrace -PIS_SNAPSHOT_BUILD=true
      - name: Upload Test Results
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit
