name: "CI & CD"
on:
  push:
    tags:
      - '*'
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20
      - name: Start Supporting Services
        run: ./scripts/setup.sh
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_STORE_USERNAME: ${{ secrets.PACKAGE_STORE_USERNAME }}
          PACKAGE_STORE_TOKEN: ${{ secrets.PACKAGE_STORE_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        with:
          gradle-version: 8.4
          arguments: clean test build publish --info --stacktrace -PIS_SNAPSHOT_BUILD=false
      - name: Upload Test Results
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit
