name: "CI & CD"
on:
  push:
    tags:
      - '*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Start Supporting Services
        run: ./scripts/setup.sh
      - name: Build & Deploy
        uses: gradle/gradle-build-action@v2
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
        with:
          gradle-version: 7.3
          arguments: clean test build artifactoryPublish --info -PIS_SNAPSHOT_BUILD=false
      - name: Upload Test Results
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit
